"""Artifact SQLAlchemy ORM model for storing metadata of outputs generated by agents."""

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import ForeignKey, Integer, String
from sqlalchemy.dialects.sqlite import JSON as SQLITE_JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON

from app.database import Base
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin, VersionMixin

if TYPE_CHECKING:
    from app.models.agent import Agent
    from app.models.organization import Organization
    from app.models.project import Project
    from app.models.task import Task
    from app.models.user import User


class Artifact(Base, UUIDPrimaryKeyMixin, TimestampMixin, VersionMixin):
    """Metadata record for an artifact stored in object storage (SeaweedFS, S3, Azure)."""

    __tablename__ = "artifacts"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    task_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("tasks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    agent_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("agents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    created_by_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    storage_key: Mapped[str] = mapped_column(String(512), nullable=False, unique=True, index=True)
    filename: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    content_type: Mapped[str] = mapped_column(
        String(128), nullable=False, default="application/octet-stream"
    )
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    sha256_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    artifact_type: Mapped[str] = mapped_column(
        String(64), nullable=False, default="OTHER", index=True
    )

    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        JSON().with_variant(SQLITE_JSON(), "sqlite"),
        nullable=False,
        default=dict,
    )

    # Relationships
    organization: Mapped["Organization"] = relationship("Organization", lazy="raise")
    project: Mapped["Project"] = relationship("Project", lazy="raise")
    task: Mapped["Task | None"] = relationship("Task", lazy="raise")
    agent: Mapped["Agent | None"] = relationship("Agent", lazy="raise")
    created_by: Mapped["User | None"] = relationship("User", lazy="raise")
